In [37]:
import numpy as numpy
import pandas as pd

In [38]:
df = pd.read_csv(r'StudentPerformanceFactors.csv')

In [39]:
df

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,High,Medium,No,7,76,Medium,Yes,1,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,8,81,Medium,Yes,3,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6,65,Low,Yes,3,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6,91,High,Yes,2,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9,94,Medium,Yes,0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

In [40]:
df.head()   # Firast five rows of table

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [41]:
df.tail()   #Last five rows of the table

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
6602,25,69,High,Medium,No,7,76,Medium,Yes,1,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,8,81,Medium,Yes,3,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6,65,Low,Yes,3,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6,91,High,Yes,2,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9,94,Medium,Yes,0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

In [42]:
df.shape   # Kitne Rows or kitne columns hai

(6607, 20)

In [43]:
df.columns

Index(['Hours_Studied', 'Attendance', 'Parental_Involvement',
       'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours',
       'Previous_Scores', 'Motivation_Level', 'Internet_Access',
       'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type',
       'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities',
       'Parental_Education_Level', 'Distance_from_Home', 'Gender',
       'Exam_Score'],
      dtype='object')

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   object
 3   Access_to_Resources         6607 non-null   object
 4   Extracurricular_Activities  6607 non-null   object
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   object
 8   Internet_Access             6607 non-null   object
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   object
 11  Teacher_Quality             6529 non-null   object
 12  School_Type                 6607 non-null   object
 13  Peer_Influence              6607 non-null   object
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   object
 16  Parental_Education_Level    6517 non-null   object
 17  Distance_from_Home          6540 non-null   object
 18  Gender                      6607 non-null   object
 19  Exam_Score                  6607 non-null   int64
dtypes: int64(7), object(13)
memory usage: 1.0+ MB

In [45]:
df.describe()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
count,6607.000000,6607.000000,6607.00000,6607.000000,6607.000000,6607.000000,6607.000000
mean,19.975329,79.977448,7.02906,75.070531,1.493719,2.967610,67.235659
std,5.990594,11.547475,1.46812,14.399784,1.230570,1.031231,3.890456
min,1.000000,60.000000,4.00000,50.000000,0.000000,0.000000,55.000000
25%,16.000000,70.000000,6.00000,63.000000,1.000000,2.000000,65.000000
50%,20.000000,80.000000,7.00000,75.000000,1.000000,3.000000,67.000000
75%,24.000000,90.000000,8.00000,88.000000,2.000000,4.000000,69.000000
max,44.000000,100.000000,10.00000,100.000000,8.000000,6.000000,101.000000

In [46]:
df.isna()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6603,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6604,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6605,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6606,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [47]:
df.isna().sum()

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

In [48]:
df[["Hours_Studied",
    "Attendance",
    "Sleep_Hours",
    "Previous_Scores",
    "Tutoring_Sessions",
    "Physical_Activity",
    "Exam_Score"]].describe()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
count,6607.000000,6607.000000,6607.00000,6607.000000,6607.000000,6607.000000,6607.000000
mean,19.975329,79.977448,7.02906,75.070531,1.493719,2.967610,67.235659
std,5.990594,11.547475,1.46812,14.399784,1.230570,1.031231,3.890456
min,1.000000,60.000000,4.00000,50.000000,0.000000,0.000000,55.000000
25%,16.000000,70.000000,6.00000,63.000000,1.000000,2.000000,65.000000
50%,20.000000,80.000000,7.00000,75.000000,1.000000,3.000000,67.000000
75%,24.000000,90.000000,8.00000,88.000000,2.000000,4.000000,69.000000
max,44.000000,100.000000,10.00000,100.000000,8.000000,6.000000,101.000000

In [49]:
std_values = df.std(numeric_only=True)
print(std_values)
print("Highest variation feature:", std_values.idxmax())

Hours_Studied         5.990594
Attendance           11.547475
Sleep_Hours           1.468120
Previous_Scores      14.399784
Tutoring_Sessions     1.230570
Physical_Activity     1.031231
Exam_Score            3.890456
dtype: float64
Highest variation feature: Previous_Scores

In [50]:
df1 = df['Exam_Score'].sum()

In [51]:
df1/6607

np.float64(67.23565914938702)

In [52]:
df.corr(numeric_only=True)

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
Hours_Studied,1.000000,-0.009908,0.010977,0.024846,-0.014282,0.004624,0.445455
Attendance,-0.009908,1.000000,-0.015918,-0.020186,0.014324,-0.022435,0.581072
Sleep_Hours,0.010977,-0.015918,1.000000,-0.021750,-0.012216,-0.000378,-0.017022
Previous_Scores,0.024846,-0.020186,-0.021750,1.000000,-0.013122,-0.011274,0.175079
Tutoring_Sessions,-0.014282,0.014324,-0.012216,-0.013122,1.000000,0.017733,0.156525
Physical_Activity,0.004624,-0.022435,-0.000378,-0.011274,0.017733,1.000000,0.027824
Exam_Score,0.445455,0.581072,-0.017022,0.175079,0.156525,0.027824,1.000000

In [53]:
# Students who study more hours consistently achieve higher exam scores, with an average increase of nearly 8 marks between the lowest and highest study groups.
df.groupby(pd.cut(df["Hours_Studied"], bins=4) , observed=False)["Exam_Score"].mean()

Hours_Studied
(0.957, 11.75]    64.256360
(11.75, 22.5]     66.526125
(22.5, 33.25]     69.045624
(33.25, 44.0]     71.841463
Name: Exam_Score, dtype: float64

In [54]:
df.groupby(pd.cut(df["Attendance"], bins=4) , observed=False)["Exam_Score"].mean()

Attendance
(59.96, 70.0]    64.330450
(70.0, 80.0]     66.431616
(80.0, 90.0]     68.335634
(90.0, 100.0]    70.155346
Name: Exam_Score, dtype: float64

In [55]:
top_25_students = df.sort_values(by='Attendance', ascending=False)
top_25_students = top_25_students.head(int(0.25 * len(df)))
print(top_25_students)

      Hours_Studied  Attendance Parental_Involvement Access_to_Resources  \
1537             17         100                 High              Medium
3402             21         100               Medium              Medium
1913             23         100                 High                 Low
5947             27         100                  Low              Medium
3560             21         100                  Low                High
...             ...         ...                  ...                 ...
2152             20          90                  Low              Medium
2164             29          90                 High                 Low
1729             31          90                 High                High
2421             27          90                  Low              Medium
3642             14          90                 High              Medium

     Extracurricular_Activities  Sleep_Hours  Previous_Scores  \
1537                         No            8               98
3402                         No            5               92
1913                        Yes            4               59
5947                        Yes            4               97
3560                         No            6               94
...                         ...          ...              ...
2152                         No            6               85
2164                        Yes            7               76
1729                         No            7               61
2421                         No            9               52
3642                        Yes            5               84

     Motivation_Level Internet_Access  Tutoring_Sessions Family_Income  \
1537              Low             Yes                  0        Medium
3402              Low             Yes                  3           Low
1913           Medium             Yes                  2        Medium
5947              Low             Yes                  4           Low
3560           Medium              No                  1          High
...               ...             ...                ...           ...
2152             High              No                  3           Low
2164              Low             Yes                  1        Medium
1729              Low             Yes                  0           Low
2421              Low              No                  2           Low
3642           Medium             Yes                  0           Low

     Teacher_Quality School_Type Peer_Influence  Physical_Activity  \
1537            High      Public       Positive                  4
3402             Low      Public       Positive                  3
1913          Medium      Public       Positive                  4
5947            High      Public       Positive                  3
3560          Medium      Public       Positive                  3
...              ...         ...            ...                ...
2152            High     Private        Neutral                  2
2164             Low      Public       Positive                  3
1729          Medium      Public       Positive                  3
2421            High      Public       Positive                  2
3642          Medium      Public       Negative                  3

     Learning_Disabilities Parental_Education_Level Distance_from_Home  \
1537                    No                  College               Near
3402                   Yes             Postgraduate               Near
1913                    No              High School               Near
5947                    No              High School               Near
3560                    No                  College           Moderate
...                    ...                      ...                ...
2152                    No                  College               Near
2164                    No              High School           Moderate
1729                    No              High School               Near
2421                   Yes                  College               Near
3642                    No             Postgraduate               Near

      Gender  Exam_Score
1537    Male          72
3402    Male          71
1913  Female          72
5947  Female          74
3560  Female          72
...      ...         ...
2152    Male          69
2164  Female          71
1729    Male          72
2421    Male          86
3642  Female          68

[1651 rows x 20 columns]

In [56]:
attendance_median = df["Attendance"].median()

high_attendance = df[df["Attendance"] > attendance_median]
low_attendance = df[df["Attendance"] <= attendance_median]

print("High Attendance Avg Score:", high_attendance["Exam_Score"].mean())
print("Low Attendance Avg Score:", low_attendance["Exam_Score"].mean())

High Attendance Avg Score: 69.24434673366834
Low Attendance Avg Score: 65.3672217353199

In [57]:
hours_median = df["Hours_Studied"].median()

high_both = df[
    (df["Attendance"] > attendance_median) & 
    (df["Hours_Studied"] > hours_median)
    ]

low_both = df[
    (df["Attendance"] <= attendance_median) & 
    (df["Hours_Studied"] <= hours_median)
]

print("High Attendance + Hight Study Avg Score : ", high_both["Exam_Score"].mean())
print("Low Attendance + Low Study Avg Score : ", low_both["Exam_Score"].mean())

High Attendance + Hight Study Avg Score :  70.80593922651934
Low Attendance + Low Study Avg Score :  64.03761061946902

In [58]:
# Above two qualities Study_Hour and Attendance matter more for an student performance
#Students who both attend regularly and study above average score nearly 7 marks higher than students who do neither. 
#Consistency in both effort and presence significantly boosts performance.

# Intercation Effect --> Two moderate drivers combining into a stronger outcome

In [59]:
df.groupby("Motivation_Level")["Exam_Score"].mean().sort_values(ascending=False)

Motivation_Level
High      67.704321
Medium    67.330648
Low       66.752194
Name: Exam_Score, dtype: float64

In [60]:
df.groupby("Teacher_Quality")["Exam_Score"].mean().sort_values(ascending=False)

Teacher_Quality
High      67.676939
Medium    67.109299
Low       66.753425
Name: Exam_Score, dtype: float64

In [61]:
df.groupby("Gender")["Exam_Score"].mean().sort_values(ascending=False)

Gender
Female    67.244898
Male      67.228894
Name: Exam_Score, dtype: float64

In [62]:
df.groupby("School_Type")["Exam_Score"].mean().sort_values(ascending=False)

School_Type
Private    67.287705
Public     67.212919
Name: Exam_Score, dtype: float64

In [63]:
df.groupby("Family_Income")["Exam_Score"].mean().sort_values(ascending=False)

Family_Income
High      67.842396
Medium    67.334959
Low       66.848428
Name: Exam_Score, dtype: float64

In [65]:
df.groupby("Parental_Education_Level")["Exam_Score"].mean().sort_values(ascending=False)

Parental_Education_Level
Postgraduate    67.970881
College         67.315737
High School     66.893577
Name: Exam_Score, dtype: float64

In [67]:
df.groupby("Tutoring_Sessions")["Exam_Score"].mean().sort_values(ascending=False)

Tutoring_Sessions
6    71.666667
7    69.857143
5    69.067961
8    69.000000
4    68.229236
3    67.894737
2    67.567010
1    66.980266
0    66.489755
Name: Exam_Score, dtype: float64

In [69]:
df.groupby("Previous_Scores")["Exam_Score"].mean().sort_values(ascending=False)

Previous_Scores
93     68.682171
95     68.627907
96     68.614379
97     68.504348
100    68.391304
94     68.316129
91     68.286765
90     68.121951
88     68.043165
99     67.984000
76     67.957143
92     67.928571
84     67.900826
98     67.870229
86     67.795620
87     67.709677
89     67.692308
77     67.680328
80     67.360902
85     67.266667
83     67.264000
69     67.255814
79     67.250000
75     67.204545
72     67.150000
81     67.096774
82     67.085106
78     67.084615
66     66.945455
74     66.925373
68     66.924242
73     66.905797
52     66.875000
57     66.872000
70     66.867647
61     66.788618
71     66.780822
67     66.776119
60     66.719008
58     66.641667
59     66.626761
64     66.469697
56     66.416667
62     66.387097
63     66.274074
53     66.270833
65     66.235294
54     66.220588
55     66.096774
51     65.912698
50     65.516129
Name: Exam_Score, dtype: float64

In [71]:
df.groupby("Sleep_Hours")["Exam_Score"].mean().sort_values(ascending=False)

Sleep_Hours
4     67.627832
5     67.297842
7     67.242964
8     67.218728
6     67.194767
9     67.149677
10    67.137821
Name: Exam_Score, dtype: float64

In [72]:
df.groupby("Physical_Activity")["Exam_Score"].mean().sort_values(ascending=False)

Physical_Activity
6    68.093750
5    67.603878
0    67.521739
4    67.313016
3    67.196071
2    67.185003
1    66.969121
Name: Exam_Score, dtype: float64

In [73]:
top_10 = df.sort_values("Exam_Score", ascending=False).head(10)
bottom_10 = df.sort_values("Exam_Score", ascending=True).head(10)

print("Top 10 average Values:\n", top_10[[
    "Attendance","Hours_Studied","Tutoring_Sessions","Previous_Scores"
]].mean())

print("\nBottom 10 average Values:\n", bottom_10[[
    "Attendance","Hours_Studied","Tutoring_Sessions","Previous_Scores"
]].mean())

Top 10 average Values:
 Attendance           88.5
Hours_Studied        21.5
Tutoring_Sessions     1.9
Previous_Scores      89.0
dtype: float64

Bottom 10 average Values:
 Attendance           62.8
Hours_Studied         8.5
Tutoring_Sessions     0.6
Previous_Scores      64.2
dtype: float64